### ISSUE TITLE
Google account creation/sign-in not working

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#71]
Pressing "Continue with Google" on the sign in screen brings up Google authentication in webview, but pressing my account to continue just takes me back to the sign in screen.

Possibly related: I'm getting "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section." as red error text underneath the email/password fields when I click Sign In or Register.

![screenshot_20181006-112855](https://user-images.githubusercontent.com/36721640/46574638-2f71e380-c95b-11e8-85fb-37ff22d05580.png)

**Comment by gmferland** [comment]
Should be fixed. I'd appreciate it if someone could test again

**Comment by crieggalder** [comment]
@gmferland, I'm showing a different error now: ![screenshot_20181006-140031](https://user-images.githubusercontent.com/36721640/46575763-b4b3c300-c970-11e8-9eae-0fe1921283f8.png)

Also, @mialknowles the Google button still doesn't work (see above for details). Do we think that's caused by the same issue as the error? Or is that a problem on the front-end?

**Comment by gmferland** [comment]
:(

**Comment by gmferland** [comment]
Try again!
